/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.AccessRight = factory(root.Bouquet.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AccessRight model module.
   * @module model/AccessRight
   * @version 4.2
   */

  /**
   * Constructs a new <code>AccessRight</code>.
   * @alias module:model/AccessRight
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>AccessRight</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessRight} obj Optional instance to populate.
   * @return {module:model/AccessRight} The populated <code>AccessRight</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
      if (data.hasOwnProperty('groupId')) {
        obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AccessRight.RoleEnum} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;
  /**
   * @member {String} groupId
   */
  exports.prototype['groupId'] = undefined;


  /**
   * Allowed values for the <code>role</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RoleEnum = {
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE",
    /**
     * value: "EXECUTE"
     * @const
     */
    "EXECUTE": "EXECUTE",
    /**
     * value: "READ"
     * @const
     */
    "READ": "READ",
    /**
     * value: "WRITE"
     * @const
     */
    "WRITE": "WRITE",
    /**
     * value: "OWNER"
     * @const
     */
    "OWNER": "OWNER"  };


  return exports;
}));


