/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExtendedType', 'model/GenericPK'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExtendedType'), require('./GenericPK'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.Col = factory(root.Bouquet.ApiClient, root.Bouquet.ExtendedType, root.Bouquet.GenericPK);
  }
}(this, function(ApiClient, ExtendedType, GenericPK) {
  'use strict';




  /**
   * The Col model module.
   * @module model/Col
   * @version 4.2
   */

  /**
   * Constructs a new <code>Col</code>.
   * @alias module:model/Col
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Col</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Col} obj Optional instance to populate.
   * @return {module:model/Col} The populated <code>Col</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = GenericPK.constructFromObject(data['pk']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('definition')) {
        obj['definition'] = ApiClient.convertToType(data['definition'], 'String');
      }
      if (data.hasOwnProperty('extendedType')) {
        obj['extendedType'] = ExtendedType.constructFromObject(data['extendedType']);
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
      if (data.hasOwnProperty('originType')) {
        obj['originType'] = ApiClient.convertToType(data['originType'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('format')) {
        obj['format'] = ApiClient.convertToType(data['format'], 'String');
      }
      if (data.hasOwnProperty('pos')) {
        obj['pos'] = ApiClient.convertToType(data['pos'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('lname')) {
        obj['lname'] = ApiClient.convertToType(data['lname'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/GenericPK} pk
   */
  exports.prototype['pk'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} definition
   */
  exports.prototype['definition'] = undefined;
  /**
   * @member {module:model/ExtendedType} extendedType
   */
  exports.prototype['extendedType'] = undefined;
  /**
   * @member {module:model/Col.RoleEnum} role
   */
  exports.prototype['role'] = undefined;
  /**
   * @member {module:model/Col.OriginTypeEnum} originType
   */
  exports.prototype['originType'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} format
   */
  exports.prototype['format'] = undefined;
  /**
   * @member {Number} pos
   */
  exports.prototype['pos'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} lname
   */
  exports.prototype['lname'] = undefined;


  /**
   * Allowed values for the <code>role</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RoleEnum = {
    /**
     * value: "DOMAIN"
     * @const
     */
    "DOMAIN": "DOMAIN",
    /**
     * value: "DATA"
     * @const
     */
    "DATA": "DATA"  };

  /**
   * Allowed values for the <code>originType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.OriginTypeEnum = {
    /**
     * value: "USER"
     * @const
     */
    "USER": "USER",
    /**
     * value: "ROLLUP"
     * @const
     */
    "ROLLUP": "ROLLUP",
    /**
     * value: "COMPARETO"
     * @const
     */
    "COMPARETO": "COMPARETO",
    /**
     * value: "GROWTH"
     * @const
     */
    "GROWTH": "GROWTH"  };


  return exports;
}));


