/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DimensionOptionPK', 'model/Expression'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DimensionOptionPK'), require('./Expression'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.DimensionOption = factory(root.Bouquet.ApiClient, root.Bouquet.DimensionOptionPK, root.Bouquet.Expression);
  }
}(this, function(ApiClient, DimensionOptionPK, Expression) {
  'use strict';




  /**
   * The DimensionOption model module.
   * @module model/DimensionOption
   * @version 4.2
   */

  /**
   * Constructs a new <code>DimensionOption</code>.
   * @alias module:model/DimensionOption
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>DimensionOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DimensionOption} obj Optional instance to populate.
   * @return {module:model/DimensionOption} The populated <code>DimensionOption</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = DimensionOptionPK.constructFromObject(data['id']);
      }
      if (data.hasOwnProperty('mandatorySelection')) {
        obj['mandatorySelection'] = ApiClient.convertToType(data['mandatorySelection'], 'Boolean');
      }
      if (data.hasOwnProperty('singleSelection')) {
        obj['singleSelection'] = ApiClient.convertToType(data['singleSelection'], 'Boolean');
      }
      if (data.hasOwnProperty('defaultSelection')) {
        obj['defaultSelection'] = Expression.constructFromObject(data['defaultSelection']);
      }
      if (data.hasOwnProperty('unmodifiableSelection')) {
        obj['unmodifiableSelection'] = ApiClient.convertToType(data['unmodifiableSelection'], 'Boolean');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('groupFilter')) {
        obj['groupFilter'] = ApiClient.convertToType(data['groupFilter'], ['String']);
      }
      if (data.hasOwnProperty('userFilter')) {
        obj['userFilter'] = ApiClient.convertToType(data['userFilter'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DimensionOptionPK} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Boolean} mandatorySelection
   * @default false
   */
  exports.prototype['mandatorySelection'] = false;
  /**
   * @member {Boolean} singleSelection
   * @default false
   */
  exports.prototype['singleSelection'] = false;
  /**
   * @member {module:model/Expression} defaultSelection
   */
  exports.prototype['defaultSelection'] = undefined;
  /**
   * @member {Boolean} unmodifiableSelection
   * @default false
   */
  exports.prototype['unmodifiableSelection'] = false;
  /**
   * @member {Boolean} hidden
   * @default false
   */
  exports.prototype['hidden'] = false;
  /**
   * @member {Array.<String>} groupFilter
   */
  exports.prototype['groupFilter'] = undefined;
  /**
   * @member {Array.<String>} userFilter
   */
  exports.prototype['userFilter'] = undefined;



  return exports;
}));


