/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccessRight', 'model/Dimension', 'model/DomainOption', 'model/DomainPK', 'model/Expression', 'model/Metric'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccessRight'), require('./Dimension'), require('./DomainOption'), require('./DomainPK'), require('./Expression'), require('./Metric'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.Domain = factory(root.Bouquet.ApiClient, root.Bouquet.AccessRight, root.Bouquet.Dimension, root.Bouquet.DomainOption, root.Bouquet.DomainPK, root.Bouquet.Expression, root.Bouquet.Metric);
  }
}(this, function(ApiClient, AccessRight, Dimension, DomainOption, DomainPK, Expression, Metric) {
  'use strict';




  /**
   * The Domain model module.
   * @module model/Domain
   * @version 4.2
   */

  /**
   * Constructs a new <code>Domain</code>.
   * @alias module:model/Domain
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>Domain</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Domain} obj Optional instance to populate.
   * @return {module:model/Domain} The populated <code>Domain</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = DomainPK.constructFromObject(data['id']);
      }
      if (data.hasOwnProperty('accessRights')) {
        obj['accessRights'] = ApiClient.convertToType(data['accessRights'], [AccessRight]);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('subject')) {
        obj['subject'] = Expression.constructFromObject(data['subject']);
      }
      if (data.hasOwnProperty('internalVersion')) {
        obj['internalVersion'] = ApiClient.convertToType(data['internalVersion'], 'Number');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = DomainOption.constructFromObject(data['options']);
      }
      if (data.hasOwnProperty('metrics')) {
        obj['metrics'] = ApiClient.convertToType(data['metrics'], [Metric]);
      }
      if (data.hasOwnProperty('dimensions')) {
        obj['dimensions'] = ApiClient.convertToType(data['dimensions'], [Dimension]);
      }
      if (data.hasOwnProperty('dynamic')) {
        obj['dynamic'] = ApiClient.convertToType(data['dynamic'], 'Boolean');
      }
      if (data.hasOwnProperty('oid')) {
        obj['oid'] = ApiClient.convertToType(data['oid'], 'String');
      }
      if (data.hasOwnProperty('objectType')) {
        obj['objectType'] = ApiClient.convertToType(data['objectType'], 'String');
      }
      if (data.hasOwnProperty('_role')) {
        obj['_role'] = ApiClient.convertToType(data['_role'], 'String');
      }
      if (data.hasOwnProperty('_vctrl')) {
        obj['_vctrl'] = ApiClient.convertToType(data['_vctrl'], 'Number');
      }
      if (data.hasOwnProperty('_children')) {
        obj['_children'] = ApiClient.convertToType(data['_children'], ['String']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
    }
    return obj;
  }

  /**
   * The object Composite Id (Primary Key)
   * @member {module:model/DomainPK} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The ACL for this object
   * @member {Array.<module:model/AccessRight>} accessRights
   */
  exports.prototype['accessRights'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/Expression} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * @member {Number} internalVersion
   */
  exports.prototype['internalVersion'] = undefined;
  /**
   * @member {module:model/DomainOption} options
   */
  exports.prototype['options'] = undefined;
  /**
   * @member {Array.<module:model/Metric>} metrics
   */
  exports.prototype['metrics'] = undefined;
  /**
   * @member {Array.<module:model/Dimension>} dimensions
   */
  exports.prototype['dimensions'] = undefined;
  /**
   * indicates if the object is automatically generated. This property can be updated.
   * @member {Boolean} dynamic
   * @default false
   */
  exports.prototype['dynamic'] = false;
  /**
   * The Object Id
   * @member {String} oid
   */
  exports.prototype['oid'] = undefined;
  /**
   * @member {String} objectType
   */
  exports.prototype['objectType'] = undefined;
  /**
   * The role of the current User (passed in the context) over this object
   * @member {module:model/Domain.RoleEnum} _role
   */
  exports.prototype['_role'] = undefined;
  /**
   * Internal version control value. (used by optimistic-locking mechanism)
   * @member {Number} _vctrl
   */
  exports.prototype['_vctrl'] = undefined;
  /**
   * @member {Array.<String>} _children
   */
  exports.prototype['_children'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;


  /**
   * Allowed values for the <code>_role</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RoleEnum = {
    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE",
    /**
     * value: "EXECUTE"
     * @const
     */
    "EXECUTE": "EXECUTE",
    /**
     * value: "READ"
     * @const
     */
    "READ": "READ",
    /**
     * value: "WRITE"
     * @const
     */
    "WRITE": "WRITE",
    /**
     * value: "OWNER"
     * @const
     */
    "OWNER": "OWNER"  };


  return exports;
}));


