/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ReferencePKObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ReferencePKObject'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.Expression = factory(root.Bouquet.ApiClient, root.Bouquet.ReferencePKObject);
  }
}(this, function(ApiClient, ReferencePKObject) {
  'use strict';




  /**
   * The Expression model module.
   * @module model/Expression
   * @version 4.2
   */

  /**
   * Constructs a new <code>Expression</code>.
   * @alias module:model/Expression
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Expression</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Expression} obj Optional instance to populate.
   * @return {module:model/Expression} The populated <code>Expression</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'String');
      }
      if (data.hasOwnProperty('references')) {
        obj['references'] = ApiClient.convertToType(data['references'], [ReferencePKObject]);
      }
    }
    return obj;
  }

  /**
   * @member {String} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {Array.<module:model/ReferencePKObject>} references
   */
  exports.prototype['references'] = undefined;



  return exports;
}));


