/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Facet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Facet'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.FacetSelection = factory(root.Bouquet.ApiClient, root.Bouquet.Facet);
  }
}(this, function(ApiClient, Facet) {
  'use strict';




  /**
   * The FacetSelection model module.
   * @module model/FacetSelection
   * @version 4.2
   */

  /**
   * Constructs a new <code>FacetSelection</code>.
   * @alias module:model/FacetSelection
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>FacetSelection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FacetSelection} obj Optional instance to populate.
   * @return {module:model/FacetSelection} The populated <code>FacetSelection</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('startIndex')) {
        obj['startIndex'] = ApiClient.convertToType(data['startIndex'], 'Number');
      }
      if (data.hasOwnProperty('facets')) {
        obj['facets'] = ApiClient.convertToType(data['facets'], [Facet]);
      }
      if (data.hasOwnProperty('compareTo')) {
        obj['compareTo'] = ApiClient.convertToType(data['compareTo'], [Facet]);
      }
      if (data.hasOwnProperty('totalSize')) {
        obj['totalSize'] = ApiClient.convertToType(data['totalSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} startIndex
   */
  exports.prototype['startIndex'] = undefined;
  /**
   * @member {Array.<module:model/Facet>} facets
   */
  exports.prototype['facets'] = undefined;
  /**
   * @member {Array.<module:model/Facet>} compareTo
   */
  exports.prototype['compareTo'] = undefined;
  /**
   * @member {Number} totalSize
   */
  exports.prototype['totalSize'] = undefined;



  return exports;
}));


