/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.StackTraceElement = factory(root.Bouquet.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StackTraceElement model module.
   * @module model/StackTraceElement
   * @version 4.2
   */

  /**
   * Constructs a new <code>StackTraceElement</code>.
   * @alias module:model/StackTraceElement
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>StackTraceElement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StackTraceElement} obj Optional instance to populate.
   * @return {module:model/StackTraceElement} The populated <code>StackTraceElement</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('methodName')) {
        obj['methodName'] = ApiClient.convertToType(data['methodName'], 'String');
      }
      if (data.hasOwnProperty('fileName')) {
        obj['fileName'] = ApiClient.convertToType(data['fileName'], 'String');
      }
      if (data.hasOwnProperty('lineNumber')) {
        obj['lineNumber'] = ApiClient.convertToType(data['lineNumber'], 'Number');
      }
      if (data.hasOwnProperty('className')) {
        obj['className'] = ApiClient.convertToType(data['className'], 'String');
      }
      if (data.hasOwnProperty('nativeMethod')) {
        obj['nativeMethod'] = ApiClient.convertToType(data['nativeMethod'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} methodName
   */
  exports.prototype['methodName'] = undefined;
  /**
   * @member {String} fileName
   */
  exports.prototype['fileName'] = undefined;
  /**
   * @member {Number} lineNumber
   */
  exports.prototype['lineNumber'] = undefined;
  /**
   * @member {String} className
   */
  exports.prototype['className'] = undefined;
  /**
   * @member {Boolean} nativeMethod
   * @default false
   */
  exports.prototype['nativeMethod'] = false;



  return exports;
}));


