/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccessRight', 'model/Attribute', 'model/Dimension', 'model/DimensionOption', 'model/ExpressionSuggestion'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AccessRight'), require('../model/Attribute'), require('../model/Dimension'), require('../model/DimensionOption'), require('../model/ExpressionSuggestion'));
  } else {
    // Browser globals (root is window)
    if (!root.Bouquet) {
      root.Bouquet = {};
    }
    root.Bouquet.DimensionsApi = factory(root.Bouquet.ApiClient, root.Bouquet.AccessRight, root.Bouquet.Attribute, root.Bouquet.Dimension, root.Bouquet.DimensionOption, root.Bouquet.ExpressionSuggestion);
  }
}(this, function(ApiClient, AccessRight, Attribute, Dimension, DimensionOption, ExpressionSuggestion) {
  'use strict';

  /**
   * Dimensions service.
   * @module api/DimensionsApi
   * @version 4.2
   */

  /**
   * Constructs a new DimensionsApi. 
   * @alias module:api/DimensionsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addOptions operation.
     * @callback module:api/DimensionsApi~addOptionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DimensionOption>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a dimension option
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:model/DimensionOption} body 
     * @param {module:api/DimensionsApi~addOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DimensionOption>}
     */
    this.addOptions = function(projectId, domainId, dimensionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling addOptions");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling addOptions");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling addOptions");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling addOptions");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DimensionOption];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/options', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAttribute operation.
     * @callback module:api/DimensionsApi~deleteAttributeCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes an Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {module:api/DimensionsApi~deleteAttributeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.deleteAttribute = function(projectId, domainId, dimensionId, attributeId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteAttribute");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling deleteAttribute");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling deleteAttribute");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling deleteAttribute");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDimension operation.
     * @callback module:api/DimensionsApi~deleteDimensionCallback
     * @param {String} error Error message, if any.
     * @param {'Boolean'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a dimension
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:api/DimensionsApi~deleteDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'Boolean'}
     */
    this.deleteDimension = function(projectId, domainId, dimensionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling deleteDimension");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling deleteDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = 'Boolean';

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteOption operation.
     * @callback module:api/DimensionsApi~deleteOptionCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DimensionOption>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a dimension option
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} optionId 
     * @param {module:api/DimensionsApi~deleteOptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DimensionOption>}
     */
    this.deleteOption = function(projectId, domainId, dimensionId, optionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling deleteOption");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling deleteOption");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling deleteOption");
      }

      // verify the required parameter 'optionId' is set
      if (optionId == undefined || optionId == null) {
        throw new Error("Missing the required parameter 'optionId' when calling deleteOption");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'optionId': optionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DimensionOption];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/options/{optionId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAttributeSuggestion operation.
     * @callback module:api/DimensionsApi~getAttributeSuggestionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExpressionSuggestion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {Object} opts Optional parameters
     * @param {String} opts.expression 
     * @param {Number} opts.offset 
     * @param {module:model/String} opts.filterType 
     * @param {module:api/DimensionsApi~getAttributeSuggestionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExpressionSuggestion}
     */
    this.getAttributeSuggestion = function(projectId, domainId, dimensionId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling getAttributeSuggestion");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling getAttributeSuggestion");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling getAttributeSuggestion");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
        'expression': opts['expression'],
        'offset': opts['offset'],
        'filterType': opts['filterType']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ExpressionSuggestion;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes-suggestion', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readAccessRightsAttribute operation.
     * @callback module:api/DimensionsApi~readAccessRightsAttributeCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AccessRight>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets an Attribute&#39;s access rights
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {module:api/DimensionsApi~readAccessRightsAttributeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AccessRight>}
     */
    this.readAccessRightsAttribute = function(projectId, domainId, dimensionId, attributeId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readAccessRightsAttribute");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readAccessRightsAttribute");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readAccessRightsAttribute");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling readAccessRightsAttribute");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AccessRight];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}/access', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readAccessRightsDimension operation.
     * @callback module:api/DimensionsApi~readAccessRightsDimensionCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AccessRight>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a dimension&#39;s access rights
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:api/DimensionsApi~readAccessRightsDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AccessRight>}
     */
    this.readAccessRightsDimension = function(projectId, domainId, dimensionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readAccessRightsDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readAccessRightsDimension");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readAccessRightsDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AccessRight];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/access', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readAllDimensions operation.
     * @callback module:api/DimensionsApi~readAllDimensionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Dimension>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Dimensions for the Domain (including child dimensions).
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {module:api/DimensionsApi~readAllDimensionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Dimension>}
     */
    this.readAllDimensions = function(projectId, domainId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readAllDimensions");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readAllDimensions");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Dimension];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readAttribute operation.
     * @callback module:api/DimensionsApi~readAttributeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Attribute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets an Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {module:api/DimensionsApi~readAttributeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Attribute}
     */
    this.readAttribute = function(projectId, domainId, dimensionId, attributeId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readAttribute");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readAttribute");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readAttribute");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling readAttribute");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Attribute;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readAttributes operation.
     * @callback module:api/DimensionsApi~readAttributesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Attribute>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets all Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:api/DimensionsApi~readAttributesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Attribute>}
     */
    this.readAttributes = function(projectId, domainId, dimensionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readAttributes");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readAttributes");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readAttributes");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Attribute];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readDimension operation.
     * @callback module:api/DimensionsApi~readDimensionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Dimension} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a dimension
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.deepread 
     * @param {module:api/DimensionsApi~readDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Dimension}
     */
    this.readDimension = function(projectId, domainId, dimensionId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readDimension");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
        'deepread': opts['deepread']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Dimension;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readOption operation.
     * @callback module:api/DimensionsApi~readOptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DimensionOption} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a dimension option
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} optionId 
     * @param {module:api/DimensionsApi~readOptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DimensionOption}
     */
    this.readOption = function(projectId, domainId, dimensionId, optionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readOption");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readOption");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readOption");
      }

      // verify the required parameter 'optionId' is set
      if (optionId == undefined || optionId == null) {
        throw new Error("Missing the required parameter 'optionId' when calling readOption");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'optionId': optionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = DimensionOption;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/options/{optionId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readOptions operation.
     * @callback module:api/DimensionsApi~readOptionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DimensionOption>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets all dimension options
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:api/DimensionsApi~readOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DimensionOption>}
     */
    this.readOptions = function(projectId, domainId, dimensionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readOptions");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readOptions");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readOptions");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DimensionOption];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/options', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the readSubDimensions operation.
     * @callback module:api/DimensionsApi~readSubDimensionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Dimension>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets the SubDimensions
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:api/DimensionsApi~readSubDimensionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Dimension>}
     */
    this.readSubDimensions = function(projectId, domainId, dimensionId, callback) {
      var postBody = null;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling readSubDimensions");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling readSubDimensions");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling readSubDimensions");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Dimension];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/subdimensions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeAccessRights operation.
     * @callback module:api/DimensionsApi~storeAccessRightsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AccessRight>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sets an Attribute&#39;s access rights
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {Array.<module:model/AccessRight>} body 
     * @param {module:api/DimensionsApi~storeAccessRightsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AccessRight>}
     */
    this.storeAccessRights = function(projectId, domainId, dimensionId, attributeId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeAccessRights");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeAccessRights");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling storeAccessRights");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling storeAccessRights");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeAccessRights");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AccessRight];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}/access', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeAccessRightsDimension operation.
     * @callback module:api/DimensionsApi~storeAccessRightsDimensionCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AccessRight>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Sets a dimension&#39;s access rights
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {Array.<module:model/AccessRight>} body 
     * @param {module:api/DimensionsApi~storeAccessRightsDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AccessRight>}
     */
    this.storeAccessRightsDimension = function(projectId, domainId, dimensionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeAccessRightsDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeAccessRightsDimension");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling storeAccessRightsDimension");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeAccessRightsDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AccessRight];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/access', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeAttribute operation.
     * @callback module:api/DimensionsApi~storeAttributeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Attribute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates an Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:model/Attribute} body 
     * @param {module:api/DimensionsApi~storeAttributeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Attribute}
     */
    this.storeAttribute = function(projectId, domainId, dimensionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeAttribute");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeAttribute");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling storeAttribute");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeAttribute");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Attribute;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeAttribute2 operation.
     * @callback module:api/DimensionsApi~storeAttribute2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/Attribute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates an Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {module:model/Attribute} body 
     * @param {module:api/DimensionsApi~storeAttribute2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Attribute}
     */
    this.storeAttribute2 = function(projectId, domainId, dimensionId, attributeId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeAttribute2");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeAttribute2");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling storeAttribute2");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling storeAttribute2");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeAttribute2");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Attribute;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeDimension operation.
     * @callback module:api/DimensionsApi~storeDimensionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Dimension} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a dimension
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {module:model/Dimension} body 
     * @param {module:api/DimensionsApi~storeDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Dimension}
     */
    this.storeDimension = function(projectId, domainId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeDimension");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Dimension;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the storeDimension2 operation.
     * @callback module:api/DimensionsApi~storeDimension2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/Dimension} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a dimension
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:model/Dimension} body 
     * @param {module:api/DimensionsApi~storeDimension2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Dimension}
     */
    this.storeDimension2 = function(projectId, domainId, dimensionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling storeDimension2");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling storeDimension2");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling storeDimension2");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling storeDimension2");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Dimension;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateAttribute operation.
     * @callback module:api/DimensionsApi~updateAttributeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Attribute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates an Attribute
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} attributeId 
     * @param {module:model/Attribute} body 
     * @param {module:api/DimensionsApi~updateAttributeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Attribute}
     */
    this.updateAttribute = function(projectId, domainId, dimensionId, attributeId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateAttribute");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling updateAttribute");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling updateAttribute");
      }

      // verify the required parameter 'attributeId' is set
      if (attributeId == undefined || attributeId == null) {
        throw new Error("Missing the required parameter 'attributeId' when calling updateAttribute");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling updateAttribute");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'attributeId': attributeId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Attribute;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/attributes/{attributeId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDimension operation.
     * @callback module:api/DimensionsApi~updateDimensionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Dimension} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a dimension
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {module:model/Dimension} body 
     * @param {module:api/DimensionsApi~updateDimensionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Dimension}
     */
    this.updateDimension = function(projectId, domainId, dimensionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateDimension");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling updateDimension");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling updateDimension");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling updateDimension");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Dimension;

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateOptions operation.
     * @callback module:api/DimensionsApi~updateOptionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/DimensionOption>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a dimension option
     * 
     * @param {String} projectId 
     * @param {String} domainId 
     * @param {String} dimensionId 
     * @param {String} optionId 
     * @param {module:model/DimensionOption} body 
     * @param {module:api/DimensionsApi~updateOptionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/DimensionOption>}
     */
    this.updateOptions = function(projectId, domainId, dimensionId, optionId, body, callback) {
      var postBody = body;

      // verify the required parameter 'projectId' is set
      if (projectId == undefined || projectId == null) {
        throw new Error("Missing the required parameter 'projectId' when calling updateOptions");
      }

      // verify the required parameter 'domainId' is set
      if (domainId == undefined || domainId == null) {
        throw new Error("Missing the required parameter 'domainId' when calling updateOptions");
      }

      // verify the required parameter 'dimensionId' is set
      if (dimensionId == undefined || dimensionId == null) {
        throw new Error("Missing the required parameter 'dimensionId' when calling updateOptions");
      }

      // verify the required parameter 'optionId' is set
      if (optionId == undefined || optionId == null) {
        throw new Error("Missing the required parameter 'optionId' when calling updateOptions");
      }

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling updateOptions");
      }


      var pathParams = {
        'projectId': projectId,
        'domainId': domainId,
        'dimensionId': dimensionId,
        'optionId': optionId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['kraken_auth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [DimensionOption];

      return this.apiClient.callApi(
        '/rs/projects/{projectId}/domains/{domainId}/dimensions/{dimensionId}/options/{optionId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
