/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.AnalyticsQuery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalyticsQuery', function() {
    it('should create an instance of AnalyticsQuery', function() {
      // uncomment below and update the code to test AnalyticsQuery
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be.a(Bouquet.AnalyticsQuery);
    });

    it('should have the property offset (base name: "offset")', function() {
      // uncomment below and update the code to test the property offset
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property bookmarkId (base name: "bookmarkId")', function() {
      // uncomment below and update the code to test the property bookmarkId
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property bbid (base name: "bbid")', function() {
      // uncomment below and update the code to test the property bbid
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property rollups (base name: "rollups")', function() {
      // uncomment below and update the code to test the property rollups
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property style (base name: "style")', function() {
      // uncomment below and update the code to test the property style
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property lazy (base name: "lazy")', function() {
      // uncomment below and update the code to test the property lazy
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property startIndex (base name: "startIndex")', function() {
      // uncomment below and update the code to test the property startIndex
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property maxResults (base name: "maxResults")', function() {
      // uncomment below and update the code to test the property maxResults
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property queryID (base name: "queryID")', function() {
      // uncomment below and update the code to test the property queryID
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property problems (base name: "problems")', function() {
      // uncomment below and update the code to test the property problems
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property groupBy (base name: "groupBy")', function() {
      // uncomment below and update the code to test the property groupBy
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property metrics (base name: "metrics")', function() {
      // uncomment below and update the code to test the property metrics
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property orderBy (base name: "orderBy")', function() {
      // uncomment below and update the code to test the property orderBy
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property beyondLimit (base name: "beyondLimit")', function() {
      // uncomment below and update the code to test the property beyondLimit
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property limit (base name: "limit")', function() {
      // uncomment below and update the code to test the property limit
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property timeframe (base name: "timeframe")', function() {
      // uncomment below and update the code to test the property timeframe
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

    it('should have the property compareTo (base name: "compareTo")', function() {
      // uncomment below and update the code to test the property compareTo
      //var instane = new Bouquet.AnalyticsQuery();
      //expect(instance).to.be();
    });

  });

}));
