/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.DataTable();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DataTable', function() {
    it('should create an instance of DataTable', function() {
      // uncomment below and update the code to test DataTable
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be.a(Bouquet.DataTable);
    });

    it('should have the property startIndex (base name: "startIndex")', function() {
      // uncomment below and update the code to test the property startIndex
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property cols (base name: "cols")', function() {
      // uncomment below and update the code to test the property cols
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property rows (base name: "rows")', function() {
      // uncomment below and update the code to test the property rows
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property objectType (base name: "objectType")', function() {
      // uncomment below and update the code to test the property objectType
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property fromCache (base name: "fromCache")', function() {
      // uncomment below and update the code to test the property fromCache
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property fromSmartCache (base name: "fromSmartCache")', function() {
      // uncomment below and update the code to test the property fromSmartCache
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property executionDate (base name: "executionDate")', function() {
      // uncomment below and update the code to test the property executionDate
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property fullset (base name: "fullset")', function() {
      // uncomment below and update the code to test the property fullset
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

    it('should have the property totalSize (base name: "totalSize")', function() {
      // uncomment below and update the code to test the property totalSize
      //var instane = new Bouquet.DataTable();
      //expect(instance).to.be();
    });

  });

}));
