/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.DimensionOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DimensionOption', function() {
    it('should create an instance of DimensionOption', function() {
      // uncomment below and update the code to test DimensionOption
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be.a(Bouquet.DimensionOption);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property mandatorySelection (base name: "mandatorySelection")', function() {
      // uncomment below and update the code to test the property mandatorySelection
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property singleSelection (base name: "singleSelection")', function() {
      // uncomment below and update the code to test the property singleSelection
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property defaultSelection (base name: "defaultSelection")', function() {
      // uncomment below and update the code to test the property defaultSelection
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property unmodifiableSelection (base name: "unmodifiableSelection")', function() {
      // uncomment below and update the code to test the property unmodifiableSelection
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property hidden (base name: "hidden")', function() {
      // uncomment below and update the code to test the property hidden
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property groupFilter (base name: "groupFilter")', function() {
      // uncomment below and update the code to test the property groupFilter
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

    it('should have the property userFilter (base name: "userFilter")', function() {
      // uncomment below and update the code to test the property userFilter
      //var instane = new Bouquet.DimensionOption();
      //expect(instance).to.be();
    });

  });

}));
