/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.ExpressionSuggestionItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExpressionSuggestionItem', function() {
    it('should create an instance of ExpressionSuggestionItem', function() {
      // uncomment below and update the code to test ExpressionSuggestionItem
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be.a(Bouquet.ExpressionSuggestionItem);
    });

    it('should have the property display (base name: "display")', function() {
      // uncomment below and update the code to test the property display
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property ranking (base name: "ranking")', function() {
      // uncomment below and update the code to test the property ranking
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property suggestion (base name: "suggestion")', function() {
      // uncomment below and update the code to test the property suggestion
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property objectType (base name: "objectType")', function() {
      // uncomment below and update the code to test the property objectType
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property valueType (base name: "valueType")', function() {
      // uncomment below and update the code to test the property valueType
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

    it('should have the property folder (base name: "folder")', function() {
      // uncomment below and update the code to test the property folder
      //var instane = new Bouquet.ExpressionSuggestionItem();
      //expect(instance).to.be();
    });

  });

}));
