/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.Facet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Facet', function() {
    it('should create an instance of Facet', function() {
      // uncomment below and update the code to test Facet
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be.a(Bouquet.Facet);
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property selectedItems (base name: "selectedItems")', function() {
      // uncomment below and update the code to test the property selectedItems
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property dimension (base name: "dimension")', function() {
      // uncomment below and update the code to test the property dimension
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property hasMore (base name: "hasMore")', function() {
      // uncomment below and update the code to test the property hasMore
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property totalSize (base name: "totalSize")', function() {
      // uncomment below and update the code to test the property totalSize
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property compositeName (base name: "compositeName")', function() {
      // uncomment below and update the code to test the property compositeName
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property done (base name: "done")', function() {
      // uncomment below and update the code to test the property done
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

    it('should have the property proxy (base name: "proxy")', function() {
      // uncomment below and update the code to test the property proxy
      //var instane = new Bouquet.Facet();
      //expect(instance).to.be();
    });

  });

}));
