/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.QueryWorkerJobStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryWorkerJobStatus', function() {
    it('should create an instance of QueryWorkerJobStatus', function() {
      // uncomment below and update the code to test QueryWorkerJobStatus
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be.a(Bouquet.QueryWorkerJobStatus);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property userID (base name: "userID")', function() {
      // uncomment below and update the code to test the property userID
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property projectPK (base name: "projectPK")', function() {
      // uncomment below and update the code to test the property projectPK
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property jobID (base name: "jobID")', function() {
      // uncomment below and update the code to test the property jobID
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property start (base name: "start")', function() {
      // uncomment below and update the code to test the property start
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property elapse (base name: "elapse")', function() {
      // uncomment below and update the code to test the property elapse
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property lineRead (base name: "lineRead")', function() {
      // uncomment below and update the code to test the property lineRead
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property chunks (base name: "chunks")', function() {
      // uncomment below and update the code to test the property chunks
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "startTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property sql (base name: "sql")', function() {
      // uncomment below and update the code to test the property sql
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

    it('should have the property elaspeTime (base name: "elaspeTime")', function() {
      // uncomment below and update the code to test the property elaspeTime
      //var instane = new Bouquet.QueryWorkerJobStatus();
      //expect(instance).to.be();
    });

  });

}));
