/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.AnalyticsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalyticsApi', function() {
    describe('cancelQuery', function() {
      it('should call cancelQuery successfully', function(done) {
        //uncomment below and update the code to test cancelQuery
        //instance.cancelQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createBookmark', function() {
      it('should call createBookmark successfully', function(done) {
        //uncomment below and update the code to test createBookmark
        //instance.createBookmark(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createBookmarkFromQuery', function() {
      it('should call createBookmarkFromQuery successfully', function(done) {
        //uncomment below and update the code to test createBookmarkFromQuery
        //instance.createBookmarkFromQuery(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('exportAnalysis', function() {
      it('should call exportAnalysis successfully', function(done) {
        //uncomment below and update the code to test exportAnalysis
        //instance.exportAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFacet', function() {
      it('should call getFacet successfully', function(done) {
        //uncomment below and update the code to test getFacet
        //instance.getFacet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getItem', function() {
      it('should call getItem successfully', function(done) {
        //uncomment below and update the code to test getItem
        //instance.getItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStatus', function() {
      it('should call getStatus successfully', function(done) {
        //uncomment below and update the code to test getStatus
        //instance.getStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listContent', function() {
      it('should call listContent successfully', function(done) {
        //uncomment below and update the code to test listContent
        //instance.listContent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAnalysis', function() {
      it('should call postAnalysis successfully', function(done) {
        //uncomment below and update the code to test postAnalysis
        //instance.postAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('runAnalysis', function() {
      it('should call runAnalysis successfully', function(done) {
        //uncomment below and update the code to test runAnalysis
        //instance.runAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scopeAnalysis', function() {
      it('should call scopeAnalysis successfully', function(done) {
        //uncomment below and update the code to test scopeAnalysis
        //instance.scopeAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewAnalysis', function() {
      it('should call viewAnalysis successfully', function(done) {
        //uncomment below and update the code to test viewAnalysis
        //instance.viewAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
