/**
 * Bouquet
 * This is Bouquet API
 *
 * OpenAPI spec version: 4.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Bouquet);
  }
}(this, function(expect, Bouquet) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Bouquet.MetricsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetricsApi', function() {
    describe('deleteMetric', function() {
      it('should call deleteMetric successfully', function(done) {
        //uncomment below and update the code to test deleteMetric
        //instance.deleteMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readAccessRightsMetric', function() {
      it('should call readAccessRightsMetric successfully', function(done) {
        //uncomment below and update the code to test readAccessRightsMetric
        //instance.readAccessRightsMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readMetric', function() {
      it('should call readMetric successfully', function(done) {
        //uncomment below and update the code to test readMetric
        //instance.readMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readMetrics', function() {
      it('should call readMetrics successfully', function(done) {
        //uncomment below and update the code to test readMetrics
        //instance.readMetrics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeAccessRightsMetric', function() {
      it('should call storeAccessRightsMetric successfully', function(done) {
        //uncomment below and update the code to test storeAccessRightsMetric
        //instance.storeAccessRightsMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeMetric', function() {
      it('should call storeMetric successfully', function(done) {
        //uncomment below and update the code to test storeMetric
        //instance.storeMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storeMetric2', function() {
      it('should call storeMetric2 successfully', function(done) {
        //uncomment below and update the code to test storeMetric2
        //instance.storeMetric2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMetric', function() {
      it('should call updateMetric successfully', function(done) {
        //uncomment below and update the code to test updateMetric
        //instance.updateMetric(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
